"""[7] Answer Synthesizer — produces the decision + justification.

The disclaimer is appended by application code, deliberately not requested
from the model, so it cannot be omitted or talked out of existing by
anything in the model's context — see docs/security-architecture.md
section 8.
"""

from collections.abc import Awaitable, Callable

from langchain_core.language_models import BaseChatModel
from pydantic import BaseModel, Field

from app.core.audit import audit_update
from app.core.llm_call import invoke_structured
from app.core.logging import get_logger
from app.prompts.answer_synthesizer_prompt import build_answer_synthesizer_prompt
from app.state.graph_state import Decision, GraphState

AGENT_NAME = "answer_synthesizer"

logger = get_logger(__name__)

DISCLAIMER = (
    "This determination was generated by an automated claims-assistance system and does not "
    "constitute a final legal or medical determination. Claimants are strongly encouraged to "
    "consult a licensed insurance adjuster or attorney before accepting or contesting this "
    "decision."
)


class _SynthesisResult(BaseModel):
    decision: Decision
    justification: str = Field(min_length=1)


def build_answer_synthesizer_node(
    chat_model: BaseChatModel,
) -> Callable[[GraphState], Awaitable[dict]]:
    synthesizer = chat_model.with_structured_output(_SynthesisResult)

    async def answer_synthesizer(state: GraphState) -> dict:
        claim_id = state["claim_id"]
        retry_count = state.get("retry_count", 0)
        logger.info(
            f"{AGENT_NAME}.started", extra={"claim_id": claim_id, "retry_count": retry_count}
        )

        redacted_chunks = state.get("redacted_chunks") or state.get("retrieved_chunks", [])

        result = await invoke_structured(
            synthesizer,
            build_answer_synthesizer_prompt(
                coverage_map=list(state.get("coverage", [])),
                fraud_signals=list(state.get("fraud_signals", [])),
                retrieved_chunks=list(redacted_chunks),
                critique=state.get("self_critique"),
            ),
            agent_name=AGENT_NAME,
            claim_id=claim_id,
            expected_type=_SynthesisResult,
        )

        logger.info(
            f"{AGENT_NAME}.completed",
            extra={"claim_id": claim_id, "decision": result.decision, "retry_count": retry_count},
        )

        return {
            "decision": result.decision,
            "justification": result.justification,
            "disclaimer": DISCLAIMER,
            **audit_update(
                AGENT_NAME,
                "synthesized_decision",
                {"decision": result.decision, "retry_count": retry_count},
            ),
        }

    return answer_synthesizer
